server:
  port: 8302
spring:
  application:
    name: microservice-order
  redis:
    host: localhost
    port: 6379
    database: 0
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/herosoft?characterEncoding=UTF-8
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      herosoft:
        order:
          mappers: debug
token:
  secret: changedagain!!!!!!!okokok


